### ISSUE TITLE
BGP Policy Primitives

### ISSUE THREAD

**Issue by riw777** [YangModels/yang#11]
Not certain if the idea was to have a separate BGP policy model or not, but if not, none of the BGP policy primitives are included here, either in set or filter. Community strings (like tags in OSPF/IS-IS) are the most important. Setting the MED, Local Pref, AS Path attributes (strip private, remove AS from path, AS Path Prepend), and various others should be included if BGP is a target.

**Comment by robshakir** [comment]
Please review openconfig/yang/bgp/bgp-policy.yang - this contains a set of augmentations that address BGP protocol specific actions - including most of the options that you mention. We did not include removal of private AS via policy currently - since we did not have an operational case that utilises this (rather than per-neighbour "remove-private-as").

**Comment by riw777** [comment]
Okay -- thanks. Will look at that one for BGP stuff.
