### ISSUE TITLE
Cisco IOS-XE17131 dependency issues on YangSuite

### ISSUE THREAD

**Issue by barry361** [YangModels/yang#1566]
I just imported Cisco iOS-xe 17131 into Yang suite and I have an issues with the module “**foo @ unknown** “. I don’t know where to find this module. Is not only on this specific version others as well. Pulling the modules from the device works fine. Getting the modules from the device itself is a better way to do so?  

Notes:
I installed YangSuite using pip install, on Ubuntu 20 Lts

Thanks,
Barr

**Comment by einarnn** [comment]
@barry361 , this isn't a problem with the YANG models stored here in YangModels/yang. I have verified that none of the modules on GitHub mention a module named `foo @ unknown`, so I do not know where this is coming from. I might suggest that you visit the YANG Suite landing page and jump onto the forums there:

https://developer.cisco.com/yangsuite/

> Getting the modules from the device itself is a better way to do so?

This really depends on the way you work. The reason vendors share their models here is to facilitate offline workflows where it is not necessary for developers to have actual devices available to download models from.

So, there is no "better" or "worse" IMO.

Since this isn't a problem with the models published here and the issue may be you YANG Suite, I'm closing this issue.
