### ISSUE TITLE
Typo in cisco/xr/662/Cisco-IOS-XR-ip-tcp-oper-sub3.yang

### ISSUE THREAD

**Issue by ellttBen** [YangModels/yang#654]
Hi,
There seems to be a typo [here](https://github.com/YangModels/yang/blob/d5bc7ab3e7c501846991277588fa0b502c70dafa/vendor/cisco/xr/662/Cisco-IOS-XR-ip-tcp-oper-sub3.yang#L1419) and [there](https://github.com/YangModels/yang/blob/d5bc7ab3e7c501846991277588fa0b502c70dafa/vendor/cisco/xr/662/Cisco-IOS-XR-ip-tcp-oper-sub3.yang#L1436) `packets` is written as `pakets`.
This might also be relevant to previous versions, I haven't manually verified it.
Have a nice day

**Comment by einarnn** [comment]
Yep, several typos. Unfortunately, unless these issues are trapped before release, they tend to be persistent as changing the name of a leaf in a YANG model is against backwards compatibility guidelines as documented in RFCs 6020 and 7950. Also, practically speaking, since these models have been released for a while they may already be in use, so changing the leaf names could end up breaking existing users.

Finally, this repository's role is to provide a public location for vendors and standards bodies to publish their models to the broader community, and cannot drive fixing any of these models. As such I will close this issue.
